
" Removes Vi compatibility. This must come first
" as it changes the functionality of other settings.
set nocompatible

filetype off             " must come before vundle
set shell=/bin/sh

"TODO: make this global and reuse it
if has('win32') || has('win16')
  let vimfiles="vimfiles"
  let vimrc="_vimrc"
else
  let vimfiles=".vim"
  let vimrc=".vimrc"
end

" Find shit
let vundle=join(["~",vimfiles,"local","vundle.vim"], "/")
let config=join(["~",vimfiles,"local","config.vim"], "/")
let settings=split(glob(join(['~',vimfiles,'local','settings','*.vim'], "/")),'\n')

" Source that shit
exe 'source' config
exe 'source' vundle

for file in settings
    exe 'source' file
endfor

filetype plugin indent on " must come after vundle

cd .
