au BufRead,BufNewFile Gulpfile,Gruntfile set filetype=js
au BufRead,BufNewFile *.json,.jscsrc,.jshintrc set filetype=json
au BufRead,BufNewFile *.styl set filetype=stylus
au BufRead,BufNewFile *.scss set filetype=scss
au BufRead,BufNewFile *.dust,*.handlebars,*.hjs,*.mustache set filetype=mustache
au BufRead,BufNewFile *.md,*.markdown set filetype=markdown
let g:html_indent_inctags = "html,body,head,tbody"
let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
