Plug g:velvet.plugins.'vim-plug/'
Plug g:velvet.plugins.'neapolitan/'
Plug 'matchit.zip'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'rstacruz/sparkup', { 'rtp': 'vim'}
Plug 'AndrewRadev/splitjoin.vim'
Plug 'rking/ag.vim'
Plug 'kien/ctrlp.vim'
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-surround'
